apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitor
spec:
  rules:
  - host: {{ prometheus_domain }}
    http:
      paths:
      - path:
        backend:
          serviceName: prometheus
          servicePort: 9090
