apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitor
spec:
  ports:
  - port: 9090
    targetPort: 9090
    name: prom-port
  selector:
    app: prometheus
